.TH ARGUMENTS  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
arguments \- list the arguments required for a command
.SH SYNOPSIS
.B arguments
.I command
.SH DESCRIPTION
Lists the arguments required to run 
.I command.
More detailed information can be found using the
.B help
command.
.SH SEE ALSO
.BR commands (1),
.BR help (1),
.BR printhelp (1),
.BR whatis (1)
