.TH AXESSCALE  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
axesscale \- set the length of plotted coordinate axes
.SH SYNOPSIS
.B axesscale
.I scale
.SH ALIASES
.B ascale
.SH DESCRIPTION
.B axesscale
sets the length of the plotted coordinate axes to 
.I scale.
The initial value of
.I scale
is 1.  Whether or not coordinate axes are plotted is controlled with the
.B showaxes
command.
.SH SEE ALSO
.BR showaxes (1)
