.TH CLEARROT  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
clearrot \- resets the viewing angle down the z-axis
.SH SYNOPSIS
.B clearrot
.SH ALIASES
.B crot
.SH DESCRIPTION
.B clearrot
resets the viewing angle to be looking down the
.IR z \-axis.
To view the particles from the new direction the 
.B clearrot
command must be followed by either the
.B view
command to maintain the same plot type or by
.B viewall,
.B viewarray,
.B viewgas,
.B viewmag,
.B viewpot,
.B viewrad,
or
.B viewstar
commands.
.SH SEE ALSO
.BR clearall (1),
.BR resetcolor (1),
.BR rotate (1),
.BR unloadall (1),
.BR unmarkall (1),
.BR unzoom (1)
