.TH CLOSEBINARY  1 "26 JUNE 2000"  "HWTipsy Release 1.0" "TIPSY COMMANDS"
.SH NAME
closemanifest \- close the currently open manifest file
.SH SYNOPSIS
.B closemanifest
.SH DESCRIPTION
.B closemanifest
closes the currently open manifest file.  This is analogous to the
.I closebinary 
command.  Manifest files are opened 
using the
.B openmanifest
command.  
.SH SEE ALSO
.BR openmanifest (1),
.BR closebinary (1)
