.TH CLOSEASCII  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
closeascii \- close the currently open ascii file
.SH SYNOPSIS
.B closeascii
.SH DESCRIPTION
.B closeascii
closes the currently open ascii file.  If no ascii file is open, an error
is generated.  Ascii files can be opened using the
.B closeascii
command.  Binary files are opened and closed using the
.B openbinary
and
.B closebinary
commands.
.SH SEE ALSO
.BR closebinary (1),
.BR openascii (1),
.BR openbinary (1)
