.TH COMMANDS  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
commands \- list the possible commands
.SH SYNOPSIS
.B commands
.I [print]
.SH DESCRIPTION
.B commands
lists the possible commands with a short description of each command.
The command usually takes no arguments unless
the command is given with the option
.I  print.
In this case the listing will be
made on the printer.  More detailed information can be found using the
.B help
command.
.SH SEE ALSO
.BR arguments (1),
.BR help (1),
.BR printhelp (1),
.BR whatis (1)
