.TH DELETEWIN  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
deletewin \- delete a window
.SH SYNOPSIS
.B deletewin
.I window-number
.SH DESCRIPTION
.B deletewin
deletes a window
.I window-number
that was created using the
.B window
command.
If
.I window-number
does not exist an error is generated.
.SH SEE ALSO
.BR hard (1),
.BR window (1)
