.TH GRAVSOFTGAS  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
gravsoftgas \- set the gravitational softening for the gas and stars 
.SH SYNOPSIS
.B gravsoftgas
.I epsgas
.SH ALIASES
.B epsgas
.SH DESCRIPTION
.B gravsoftgas
sets the value of the gravitational softening length for the gas and star
particles to
.I epsgas
for use in commands such as 
.B rotationcurve
or
.B viewgas.
The softening length is in system units.

.SH SEE ALSO
.BR coolconstants (1),
.BR formconstants (1),
.BR gravsoft (1),
.BR lumconstants (1),
.BR redshift (1),
.BR rotationcurve (1),
.BR viewgas (1),
.BR viscconstants (1)
