.TH GRAVSOFT  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
gravsoft \- set the gravitational softening for the dark matter
.SH SYNOPSIS
.B gravsoft
.I eps
.SH ALIASES
.B eps
.SH DESCRIPTION
.B gravsoft
sets the value of the gravitational softening length for the dark particles
to
.I eps
for use in commands such as 
.B rotationcurve.
The softening length is in system units.

.SH SEE ALSO
.BR coolconstants (1),
.BR formconstants (1),
.BR gravsoftgas (1),
.BR lumconstants (1),
.BR redshift (1),
.BR rotationcurve (1),
.BR viscconstants (1)
