.TH HELP  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
help \- display useful information about commands on the screen
.SH SYNOPSIS
.B help
.I command
.SH ALIASES
.B man
.SH DESCRIPTION
.B help
displays useful information about
.I command
on the screen.
For general information about
.B TIPSY
type
.B ``help tipsy <return>''
or just
.B ``help <return>''.
To print a hard copy use the
.B printhelp 
command. To print a short description of a particular command use the
.B whatis
command.
To print a brief description of all the commands use the
.B commands
command.  To find the correct arguments for a command use the
.B arguments
command.
.SH SEE ALSO
.BR arguments (1),
.BR commands (1),
.BR printhelp (1),
.BR whatis (1)
