.TH LUMCONSTANTS  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
lumconstants \- set the constants related to stellar luminosities
.SH SYNOPSIS
.B lumconstants
.I msolunit
.I kpcunit
.SH ALIASES
.B lconst
.SH DESCRIPTION
.B lumconstants
sets the values of constants that are related to calculating 
stellar luminosities for use in commands such as 
.B vista
or
.B viewstar.
.RS
.TP 3
.I msolunit
is the system mass unit in solar masses.
.TP 3
.I kpcunit
is the system length unit in kiloparsecs.
.RE
.SH SEE ALSO
.BR coolconstants (1),
.BR formconstants (1),
.BR gravsoft (1),
.BR gravsoftgas (1),
.BR redshift (1),
.BR viscconstants (1),
.BR viewstar (1),
.BR vista (1)
