.TH PRINTHELP  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
printhelp \- print useful information about commands on the printer
.SH SYNOPSIS
.B printhelp
.I command
.SH ALIASES
.B phelp
.SH DESCRIPTION
.B printhelp
prints useful information about
.I command
on the printer.
For general information about
.B TIPSY
type
.B ``printhelp tipsy <return>''
or just
.B ``printhelp <return>''.
To print the information on the screen use the
.B help 
command.  To print a short description of a particular command use the
.B whatis
command.
To print a brief description of all the commands use the
.B commands
command.  To find the correct arguments for a command use the
.B arguments
command.
.SH SEE ALSO
.BR arguments (1),
.BR commands (1),
.BR help (1),
.BR whatis (1)
