.TH PRINT  1 "10 JULY 2000"  "HWTipsy Release 1.0" "TIPSY COMMANDS"
.SH NAME
print \- print text to screen
.SH SYNOPSIS
.B print
.I text 
and/or 
.I variables.
.SH DESCRIPTION
.B print
puts text on the screen, somewhat like Unix echo.  The
values of variables are substituted before printing.
.SH SEE ALSO
.BR set (1)
