.TH READBINARRAY  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
readbinarray \- read an array from a binary file
.SH SYNOPSIS
.B readbinarray
.I filename type
.SH DESCRIPTION
.B readbinarray
reads in an array of scalars for each particle from the file
.I filename
for use by commands like
.B arraystat,
.B markarray,
and
.B viewarray.
The 
.I type
parameter is either
.I int, float
or
.I double
and indicates the format of the file.

The file
.I filename
must be a binary file. The file should be of the form:
.LP
.RS
.TP 3
ntotal
.TP 3
array_value(i), i = 1 to ntotal
.RE

where ntotal is the total number of particles.
Therefore, the total file length is sizeof(int) + ntotal*sizeof(format)
bytes.

The
.B readvector
command is used to read in vectors.
.SH SEE ALSO
.BR arraystat (1),
.BR markarray (1),
.BR readvector (1),
.BR viewarray (1)
