.TH RESETCOLOR  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
resetcolor \- reset the colormap
.SH SYNOPSIS
.B resetcolor
.I [ where ]
.SH ALIASES
.B rcol
.SH DESCRIPTION
.B resetcolor
resets the colormap to its original value.  If the optional argument
.I where
is given as a value between 0.0 and 1.0, the colorbar will be scrolled
by the corresponding fraction.
.SH SEE ALSO
.BR clearall (1),
.BR clearrot (1),
.BR resetcolor (1),
.BR unloadall (1),
.BR unmarkall (1),
.BR unzoom (1)
