.TH RESETCOLOR  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
resetcolor \- reset the colormap
.SH SYNOPSIS
.B resetcolor
.SH ALIASES
.B rcol
.SH DESCRIPTION
.B resetcolor
resets the colormap to its original value. The command takes no arguments.
.SH SEE ALSO
.BR clearall (1),
.BR clearrot (1),
.BR resetcolor (1),
.BR unloadall (1),
.BR unmarkall (1),
.BR unzoom (1)
