.TH SET  1 "10 JULY 2000"  "HWTipsy Release 1.0" "TIPSY COMMANDS"
.SH NAME
set \- set a global variable
.SH SYNOPSIS
.B set
.I variable = expression
.SH DESCRIPTION
.B set
sets a variable to a value.  There are two kinds of expressions:
string constants, and mathematical expressions.  The latter are
passed to a calculator routine, treating all numeric constants as floats.
An optional C-language formatting code may appear before the equal sign
to control the number of digits resulting from mathematical expressions.
Examples:
   set $name = Bruce
   set $x = (2^3 + 1.9)
   set $z %.3f = 1./3.
.br
Any time the name of a variable appears in a subsequent command, its
value will be substituted instead.  Variables are identified by dollar
signs, even when you are assigning their value;
thus their syntax is like perl and unlike that of shell scripts.  
To distinguish them from macro parameters, they must contain
alphabetic characters.  Braces may be used to surround the variable
name (not including the dollar sign) to delineate the end of the name.
  openb simulation_${name}.bin
  setbox 1 com 0 gas $size $size $size

Variables can be printed to the screen with the 
.I print
command.
Variables can be deleted with the 
.I delete
command.
.SH SEE ALSO
.BR delete (1),
.BR print (1)
