.TH SETBOX  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
setbox \- make and load a box from the command line
.SH SYNOPSIS
.B setbox
.I box
.I xmin
.I xmax
.I ymin
.I ymax
.I zmin
.I zmax
.SH DESCRIPTION
.B setbox
is used to define the boundaries of
.I box
through the command line.  The requested box must be between 1 and
.I MAXBOX
or an error will be generated.  The value of
.I MAXBOX
can be found by using the 
.B version
command.  The box extends from
.I xmin
to
.I xmax
in the x direction, from
.I ymin
to 
.I ymax
in the y direction, and from
.I zmin
to 
.I zmax
in the z direction.

Once a box is made and loaded it still isn't the active box for plotting
until the
.B activatebox
command is used.
Boxes are removed using the
.B unload
command.

Boxes with numbers greater than box 0 cannot be made until
box 0 is loaded.
Boxes can also be made and loaded using the
.B makebox
and
.B setsphere
commands.  Box 0 can also be made and loaded using the
.B loadall
command. Boxes can be plotted using the
.B showboxes
command.
.SH SEE ALSO
.BR activatebox(1),
.BR loadall(1),
.BR makebox(1),
.BR setsphere(1),
.BR showboxes(1),
.BR unload(1),
.BR version(1)
