.TH SHELL  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
shell \- execute a system command
.SH SYNOPSIS
.B shell
.I <system command>
.SH DESCRIPTION
.B shell
allows the user to execute a 
.I system command
from the TIPSY command line.
This is useful when making movies from long macro scripts using the
.B macro
command.
.SH SEE ALSO
.BR macro (1)
