.TH SHOWBOXES  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
showboxes \- turn display of box edges off or on
.SH SYNOPSIS
.B showboxes
.I yes/no
.SH ALIASES
.B sbox
.SH DESCRIPTION
.B showboxes
takes a
.I yes
or
.I no
argument.  The
.I yes
argument will cause the edges of all the loaded boxes to be plotted in green.
The 
.I no
argument causes the boxes not to be plotted. This is the default.
The arguments
.I yes
or
.I no
can be abbreviated
.I y
or 
.I n.
.SH SEE ALSO
.BR showaxes (1),
.BR showdark (1),
.BR showgas (1),
.BR showstar (1),
.BR showvec (1),
.BR showvel (1)
