.TH SHOWGAS  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
showgas \- turn display of gas particles off or on
.SH SYNOPSIS
.B showgas
.I yes/no
.SH ALIASES
.B sgas
.SH DESCRIPTION
.B showgas
takes a
.I yes
or
.I no
argument.  The
.I yes
argument allows gas particles to be plotted.  This is the default.
The
.I no
argument causes gas particles not to be plotted.
The arguments
.I yes
or
.I no
can be abbreviated
.I y
or
.I n.
.SH SEE ALSO
.BR showaxes (1),
.BR showboxes (1),
.BR showdark (1),
.BR showstar (1),
.BR showvec (1),
.BR showvel (1)
