.TH SHOWAXES  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
showaxes \- turn axes display off or on
.SH SYNOPSIS
.B showaxes
.I yes/no
.SH ALIASES
.B saxes
.SH DESCRIPTION
.B showaxes
takes a
.I yes
or
.I no
argument.  The
.I yes
argument causes coordinate axes to be plotted in green in plots. The
.I no
argument causes the axes not be plotted.  This is the default.
The arguments
.I yes
or
.I no
can be abbreviated
.I y
or
.I n.
The size of the axes are controlled using the
.B
axesscale
command.
.SH SEE ALSO
.BR axesscale (1),
.BR showboxes (1),
.BR showdark (1),
.BR showgas (1),
.BR showstar (1),
.BR showvec (1),
.BR showvel (1)
