.TH SHOWSTAR  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
showstar \- turn display of star particles off or on
.SH SYNOPSIS
.B showstar
.I yes/no
.SH ALIASES
.B sstar
.SH DESCRIPTION
.B showstar
takes a
.I yes
or
.I no
argument.  The
.I yes
argument allows star particles to be plotted.  This is the default.
The
.I no
argument causes star particles not to be plotted.
The arguments
.I yes
or
.I no
can be abbreviated
.I y
or
.I n.
.SH SEE ALSO
.BR showaxes (1),
.BR showboxes (1),
.BR showdark (1),
.BR showgas (1),
.BR showvec (1),
.BR showvel (1)
