.TH SMOOTH  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
smooth \- set parameters for smoothing
.SH SYNOPSIS
.B smooth
.I ball_size n_smooth
.SH DESCRIPTION
.B Smooth
sets the value of the ball size 
to
.I ball_size
or the number of particles to smooth over
to
.I n_smooth
for use in commands such as
.B vista
that require estimating smooth field parameters.  If
.I ball_size
is non-negative,
.I n_smooth
is ignored.  Otherwise, the smoothing length for each particle is
adjusted such that it contains
.I n_smooth
particles.

.SH SEE ALSO
.BR coolconstants (1),
.BR formconstants (1),
.BR gravsoft (1),
.BR gravsoftgas (1),
.BR lumconstants (1),
.BR redshift (1),
.BR rotationcurve (1),
.BR viscconstants (1)
