.TH UNLOAD  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
unload \- unload a box
.SH SYNOPSIS
.B unload
.I box
.SH DESCRIPTION
.B unload
is used to unload a box.  The requested box must be between 0 and
.I MAXBOX.
If the box is marked, then it will be unmarked.
.SH SEE ALSO
.BR activatebox(1),
.BR loadall(1),
.BR makebox(1),
.BR setbox(1),
.BR setsphere(1),
.BR showboxes(1)
