.TH UNMARKALL  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
unmarkall \- unmark all particles
.SH SYNOPSIS
.B unmarkall
.SH ALIASES
.B umall
.SH DESCRIPTION
.B unmarkall
makes all particles unmarked.
.SH SEE ALSO
.BR markarray (1),
.BR markbox (1),
.BR markgal (1),
.BR markstat (1),
.BR readmark (1),
.BR unmarkbox (1),
.BR writemark (1)
