.TH UNMARKBOX  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
unmarkbox \- unmark particles in a box
.SH SYNOPSIS
.B unmarkbox
.I box-number
.SH ALIASES
.B umbox
.SH DESCRIPTION
.B unmarkbox
unmarks the particles in box
.I box-number.

.SH SEE ALSO
.BR markarray (1),
.BR markbox (1),
.BR markgal (1),
.BR markstat (1),
.BR readmark (1),
.BR unmarkall (1),
.BR writemark (1)
