.TH UNZOOM  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
unzoom \- reset zoom factor to 1
.SH SYNOPSIS
.B unzoom
.SH DESCRIPTION
.B unzoom
resets the zoom factor of the display to 1.  This undoes the effect of
the
.B zoom
command and the zoom scrollbar.
.SH SEE ALSO
.BR zoom(1)
