'\" e
.EQ
delim $$
.EN
.TH COOLCONSTANTS  1 "22 MARCH 1994"  "KQ Release 2.0" "TIPSY COMMANDS"
.SH NAME
uvfield \- set the values of constants related to the uv background field
.SH SYNOPSIS
.B uv
.I uv_type
.I jnu21
.I alphaj
.SH ALIASES
.B uv
.SH DESCRIPTION
.I jnu21
is the flux of the background radiation field in units of $10 sup {-21}$
$ergs sup {-1}$ $cm sup {-2}$ $Hz sup {-1}$ $sr sup {-1}$.
.eqn
.TP 3
.I alphaj
is the slope of the UV background spectrum, j = jnu21*(nu/nu_L)**(-alphaj).
.RE

.SH SEE ALSO
.BR coolconstants (1),
.BR formconstants (1),
.BR gravsoft (1),
.BR gravsoftgas (1),
.BR lumconstants (1),
.BR redshift (1),
.BR viscconstants (1)
