.TH VELSCALE  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
velscale \- scale the length of velocities or vectors
.SH SYNOPSIS
.B velscale
.I scale
.SH ALIASES
.B vscale
.SH DESCRIPTION
.B velscale 
takes an argument 
.I scale 
which is a value that determines the length of velocities or vectors.
.SH SEE ALSO
.B showvel(1),
.B showvec(1),