.TH XALL  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
xall \- do an all plot projected along the y axis
.SH SYNOPSIS
.B xall
.SH DESCRIPTION
.B xall
is a command that redraws the plot showing all particles in the simulation
and projects it along the x axis.  This command takes no arguments.  It also 
initializes box 0 when first loading a file using
.B openbinary
and 
.B loadbinary.
.SH SEE ALSO
.BR yall(1),
.BR zall(1),
.BR loadbinary(1),
.BR openbinary(1)
