.TH XVERBOSE  1 "24 JUNE 2000"  "HWTipsy Release 1.0" "TIPSY COMMANDS"
.SH NAME
xverbose \- turn verbose x control mode on or off
.SH SYNOPSIS
.B xverbose
.I yes/no
.SH DESCRIPTION
.B xverbose
takes a
.I yes
or
.I no
argument.  (Also 
.I y/n
or 
.I on/off.) 
If the mode is turned on, every time you change the current view by means
of the scrollbars or mouse clicks, the command to make that change will
be reported on the screen.  This mode could be useful in making movies.
.SH SEE ALSO
.BR rotate (1),
.BR zoom (1)
