.TH ZALL  1 "22 MARCH 1994"  "Katz and Quinn Release 2.0" "TIPSY COMMANDS"
.SH NAME
zall \- do an all plot projected along the y axis
.SH SYNOPSIS
.B zall
.SH DESCRIPTION
.B zall
is a command that redraws the plot showing all particles in the simulation
and projects it along the z axis.  This command takes no arguments.  It also 
initializes box 0 when first loading a file using
.B openbinary
and 
.B loadbinary.
.SH SEE ALSO
.BR xall(1),
.BR yall(1),
.BR loadbinary(1),
.BR openbinary(1)
